name: DeployService
on:
  push: # 监听调用时机为push事件
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    steps:
      - name: 拉取代码 # 步骤名字
        uses: actions/checkout@master # 使用 actions/checkout 库拉取最新源码

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 安装 Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: 项目安装依赖
      #   run: |
      #     cd packages/nest-app
      #     npm install --force
      #     npm run build

      # - name: 项目打包构建
      #   env:
      #     NODE_OPTIONS: --max_old_space_size=4096
      #   run: pnpm build
      - name: 登录到镜像仓库
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 打包以及推送Docker镜像
        uses: docker/build-push-action@v2
        with:
          push: true
          context: packages/nest-app
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{secrets.DOCKER_NAMESPACE}}/${{secrets.DOCKER_WAREHOUSE_NAME}}:latest

      - name: 执行远程脚本命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop ${{secrets.DOCKER_WAREHOUSE_NAME}} || true
            docker rm ${{secrets.DOCKER_WAREHOUSE_NAME}} || true
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{secrets.DOCKER_NAMESPACE}}/${{secrets.DOCKER_WAREHOUSE_NAME}}:latest
            docker rmi $(docker image ls -f dangling=true | grep ${{secrets.DOCKER_WAREHOUSE_NAME}} | awk '{print $3}')
            docker run -d --name ${{secrets.DOCKER_WAREHOUSE_NAME}} -p 1119:1119 -e DATABASE_URL=file:./dev.db -e HOST=https://cyber-offer-sacrifices-api.hacxy.cn -e PORT=1119 ${{ secrets.DOCKER_REGISTRY }}/${{secrets.DOCKER_NAMESPACE}}/${{secrets.DOCKER_WAREHOUSE_NAME}}:latest

      # - name: 移动产物至到服务器
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     source: "packages/nest-app"
      #     target: "/${{secrets.SSH_USERNAME}}/Projects/.cyber-offer-sacrifices-api_temp/"
      #     rm: true
      #     strip_components: 2

      # - name: 执行远程脚本命令
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     script: |
      #       rm -rf /${{secrets.SSH_USERNAME}}/Projects/cyber-offer-sacrifices-api/*
      #       cp -rf /${{secrets.SSH_USERNAME}}/Projects/.cyber-offer-sacrifices-api_temp/*  /${{secrets.SSH_USERNAME}}/Projects/cyber-offer-sacrifices-api/
      - run: echo "部署完成！"
